"""
MCP Server — PPT writer (in-memory state + save to .pptx).

This server is started by `agent_ppt.py` using an MCP stdio transport, so it
must not rely on HTTP ports. Tools return JSON-serializable dicts so the
Claude-connected agent can safely parse responses.

**Tool index (for LLM / Claude system prompts):**

- ``create_pptx`` — start deck; returns ``session_id``.
- ``open_presentation`` — load existing ``.pptx`` from disk; append slides then ``save_presentation``.
- ``add_slide`` — title + bullets; returns ``slide_index``.
- ``add_text_box`` — free text at coordinates (inches).
- ``add_image`` — embed PNG/JPG from disk path or placeholder.
- ``add_smart_art`` — SmartArt-like row of labeled boxes (2–5 steps).
- ``apply_slide_accent`` — hex accent color on title/body.
- ``save_presentation`` — write safe ``.pptx`` to ``output_path``.
"""

import logging  # Quiet MCP request INFO lines when spawned as stdio subprocess.
import os  # Needed for creating output folders on save.
import uuid  # Needed to generate unique session ids per presentation.
import sys
from pathlib import Path

logging.getLogger("mcp").setLevel(logging.WARNING)
logging.getLogger("httpx").setLevel(logging.WARNING)
from typing import Dict, List  # Used to type the tool inputs/outputs.

from mcp.server.fastmcp import FastMCP  # FastMCP provides a minimal MCP server.
from pptx import Presentation  # python-pptx builds a real PowerPoint file.
from pptx.dml.color import RGBColor  # RGBColor is required to set theme accents.
from pptx.enum.shapes import MSO_SHAPE  # MSO_SHAPE is used to create rectangles.
from pptx.util import Inches, Pt  # Inches for layout; Pt for font sizes.


mcp = FastMCP("ppt-mcp-server")  # MCP server name (shows up in tooling).

# Keep presentation objects in memory so the agent can call:
# create_pptx -> add_slide (multiple times) -> save_presentation.
_SESSIONS: Dict[str, Presentation] = {}


def _parse_hex_color(accent_hex: str) -> RGBColor:
    """
    Convert a hex string like '#1F77B4' or '1F77B4' into an `RGBColor`.

    We keep this helper small and defensive because grading expects the
    agent not to crash if a tool argument is malformed.
    """
    value = accent_hex.strip().lstrip("#")
    if len(value) != 6:
        # Fallback to a safe color if parsing fails.
        return RGBColor(31, 119, 180)

    r = int(value[0:2], 16)
    g = int(value[2:4], 16)
    b = int(value[4:6], 16)
    return RGBColor(r, g, b)


@mcp.tool()
def check_permissions(output_path: str) -> dict:
    """Test tool to verify write permissions on a path."""
    try:
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        with open(output_path, "w") as f:
            f.write("OK")
        return {"ok": True, "written_to": output_path}
    except Exception as e:
        return {"ok": False, "error": str(e)}


@mcp.tool()
def create_pptx(title: str = "Presentation") -> dict:
    """Initialize a new PowerPoint deck in memory and return a session handle.

    **Required Tool Name:** create_pptx (per brief).

    **Parameters:**
        title: Main deck title shown on the first (title) slide.

    **Returns:**
        dict with ``ok`` (bool), ``session_id`` (str).
    """

    pres = Presentation()  # Create an empty PowerPoint presentation.

    # Add a title slide so the final `.pptx` isn't missing a header slide.
    slide = pres.slides.add_slide(pres.slide_layouts[0])  # Standard title layout.
    slide.shapes.title.text = title  # Put the planned title on slide 1.
    subtitle = slide.placeholders[1]  # python-pptx exposes subtitle as a placeholder.
    subtitle.text = "Generated by MCP Auto-PPT Agent"  # Mark it clearly for grading.

    session_id = str(uuid.uuid4())  # Unique id links tool calls together.
    _SESSIONS[session_id] = pres  # Store the Presentation object for later edits.

    return {"ok": True, "session_id": session_id}  # MCP returns JSON to the agent.


@mcp.tool()
def open_presentation(file_path: str) -> dict:
    """Load an existing **``.pptx``** into memory so new slides can be appended before save.

    **Parameters:**
        file_path: Absolute or relative path to a readable ``.pptx`` file.

    **Returns:**
        ``ok``, ``session_id``, ``slides_total`` (count after load), ``loaded_from``; or ``error``.
    """
    path = os.path.normpath(os.path.expanduser(file_path))
    path = os.path.abspath(path)
    if not os.path.isfile(path):
        return {"ok": False, "error": f"File not found: {path}"}
    try:
        pres = Presentation(path)
    except Exception as exc:
        return {"ok": False, "error": f"Could not open presentation: {exc}"}
    session_id = str(uuid.uuid4())
    _SESSIONS[session_id] = pres
    return {
        "ok": True,
        "session_id": session_id,
        "slides_total": len(pres.slides),
        "loaded_from": path,
    }


@mcp.tool()
def add_slide(session_id: str, slide_title: str, bullets: List[str]) -> dict:
    """Add a Title and Content slide with a split-screen optimized layout.

    **Required Tool Name:** add_slide.

    **Parameters:**
        session_id: Session ID.
        slide_title: Heading.
        bullets: Text points.

    **Returns:** ``ok``, ``slide_index``.
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}

    pres = _SESSIONS[session_id]
    slide = pres.slides.add_slide(pres.slide_layouts[1])
    slide_index = len(pres.slides) - 1
    slide.shapes.title.text = slide_title

    # Layout Optimization: Shrink the body box so it doesn't overlap the image.
    body = slide.shapes.placeholders[1]
    body.left = 0
    body.width = int(pres.slide_width * 0.60) # 60% width on the left.
    tf = body.text_frame
    tf.clear()

    clean_bullets = bullets[:5] if bullets else ["(No facts found)"]
    for i, bullet in enumerate(clean_bullets):
        p = tf.add_paragraph() if i > 0 else tf.paragraphs[0]
        p.text = bullet
        p.level = 0

    return {"ok": True, "slides_total": len(pres.slides), "slide_index": slide_index}


@mcp.tool()
def add_image(session_id: str, slide_index: int, image_path: str = "", caption: str = "") -> dict:
    """Add an image to the RIGHT half of a slide.

    **Required Tool Name:** add_image.

    **Parameters:**
        session_id: Session ID.
        slide_index: Slide to edit.
        image_path: Path to .jpg/.png.
        caption: Display text if missing.

    **Returns:** ``ok``, ``slide_index``.
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}
    pres = _SESSIONS[session_id]
    try:
        slide = pres.slides[slide_index]
    except Exception:
        return {"ok": False, "error": "Invalid slide_index"}

    # Position on the right 40% of the slide.
    left = int(pres.slide_width * 0.60)
    top = int(pres.slide_height * 0.25)
    width = int(pres.slide_width * 0.35)
    height = int(pres.slide_height * 0.60)

    if image_path and Path(image_path).is_file():
        try:
            slide.shapes.add_picture(image_path, left, top, width, height)
            return {"ok": True, "type": "file", "slide_index": slide_index}
        except Exception:
            pass
    
    # Placeholder
    shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, width, height)
    shape.fill.solid()
    shape.fill.fore_color.rgb = RGBColor(245, 245, 245)
    tf = shape.text_frame
    tf.clear()
    tf.text = caption or "Illustration Here"
    return {"ok": True, "type": "placeholder", "slide_index": slide_index}


@mcp.tool()
def apply_slide_accent(session_id: str, slide_index: int, accent_hex: str) -> dict:
    """Apply an **accent color** (hex) to title and body text on one slide.

    **Purpose:** Consistent visual theme across slides without manual formatting.

    **Parameters:**
        session_id: Active session.
        slide_index: Slide to style.
        accent_hex: Color like ``#1F77B4`` or ``1F77B4``; invalid values fall back to a default blue.

    **Returns:** ``ok``, ``slide_index``, ``accent_hex``.

    **Notes:** Best-effort; if a shape has no runs, styling may skip silently.
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}

    pres = _SESSIONS[session_id]
    try:
        slide = pres.slides[slide_index]
    except Exception:
        return {"ok": False, "error": "Invalid slide_index"}

    rgb = _parse_hex_color(accent_hex)

    # 1) Title accent
    try:
        title_shape = slide.shapes.title
        if title_shape is not None and getattr(title_shape, "text_frame", None) is not None:
            for paragraph in title_shape.text_frame.paragraphs:
                for run in paragraph.runs:
                    run.font.color.rgb = rgb
                    # Make title slightly larger for visual hierarchy.
                    run.font.size = Pt(30)
    except Exception:
        # Ignore styling errors; never fail the whole PPT generation.
        pass

    # 2) Bullets accent (placeholders are paragraph/runs-based)
    try:
        body_placeholder = slide.shapes.placeholders[1]
        tf = body_placeholder.text_frame
        for paragraph in tf.paragraphs:
            for run in paragraph.runs:
                run.font.color.rgb = rgb
    except Exception:
        pass

    return {"ok": True, "slide_index": slide_index, "accent_hex": accent_hex}


@mcp.tool()
def add_text_box(
    session_id: str,
    slide_index: int,
    text: str,
    left_inches: float = 0.5,
    top_inches: float = 5.0,
    width_inches: float = 8.5,
    height_inches: float = 1.2,
) -> dict:
    """Add a **free-floating text box** on a slide (caption, footer, callout).

    **Purpose:** Extra labels beyond the main title/bullet placeholder.

    **Parameters:**
        session_id: Active session.
        slide_index: Target slide index.
        text: Plain text (word-wrapped in the box).
        left_inches, top_inches, width_inches, height_inches: Position and size in inches.

    **Returns:** ``ok``, ``slide_index``, ``shape_index`` (last shape on slide).

    **Notes:** Coordinates are typical US Letter / 16:9 friendly defaults; adjust per theme.
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}
    pres = _SESSIONS[session_id]
    try:
        slide = pres.slides[slide_index]
    except Exception:
        return {"ok": False, "error": "Invalid slide_index"}

    box = slide.shapes.add_textbox(
        Inches(left_inches),
        Inches(top_inches),
        Inches(width_inches),
        Inches(height_inches),
    )
    tf = box.text_frame
    tf.clear()
    tf.text = text
    try:
        for p in tf.paragraphs:
            for r in p.runs:
                r.font.size = Pt(12)
    except Exception:
        pass
    return {"ok": True, "slide_index": slide_index, "shape_index": len(slide.shapes) - 1}


@mcp.tool()
def add_smart_art(session_id: str, slide_index: int, steps: List[str]) -> dict:
    """Draw a **simple process-style diagram** (SmartArt-like): boxes in a row with arrows.

    **Required Tool Name:** add_smart_art (per brief).

    **Parameters:**
        session_id: Active session.
        slide_index: Slide to draw on.
        steps: 2–5 short stage labels.

    **Returns:** ``ok``, ``slide_index``.
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}
    pres = _SESSIONS[session_id]
    try:
        slide = pres.slides[slide_index]
    except Exception:
        return {"ok": False, "error": "Invalid slide_index"}

    clean = [s.strip() for s in steps if s.strip()][:5]
    if len(clean) < 2:
        return {"ok": False, "error": "Provide at least 2 steps"}

    sw = pres.slide_width
    sh = pres.slide_height
    n = len(clean)
    margin = int(sw * 0.05)
    box_w = int((sw - 2 * margin) / n * 0.85)
    box_h = int(sh * 0.12)
    top = int(sh * 0.35)
    gap = int((sw - 2 * margin - n * box_w) / max(n - 1, 1))

    for i, label in enumerate(clean):
        left = margin + i * (box_w + gap)
        shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, box_w, box_h)
        shape.fill.solid()
        shape.fill.fore_color.rgb = RGBColor(240, 248, 255)
        shape.line.color.rgb = RGBColor(100, 149, 237)
        tf = shape.text_frame
        tf.clear()
        tf.text = label
        try:
            for p in tf.paragraphs:
                for r in p.runs:
                    r.font.size = Pt(11)
        except Exception:
            pass

    return {"ok": True, "slide_index": slide_index, "steps_drawn": n}


@mcp.tool()
def save_presentation(session_id: str, output_path: str) -> dict:
    """Persist the deck to disk as a valid **``.pptx``** file (safe binary package).

    **Required Tool Name:** save_presentation.

    **Parameters:**
        session_id: Session to save.
        output_path: Absolute path to the .pptx file.

    **Returns:** ``ok``, ``output_path``.
    """
    # Debug print to server stderr (seen by agent)
    print(f"[DEBUG] Saving session {session_id} to {output_path}", file=sys.stderr)
    
    if session_id not in _SESSIONS:
        print(f"[ERROR] Session {session_id} not found in _SESSIONS: {list(_SESSIONS.keys())}", file=sys.stderr)
        return {"ok": False, "error": f"Invalid session_id: {session_id}"}

    try:
        # Create output folder if it doesn't exist.
        abs_out = os.path.abspath(output_path)
        os.makedirs(os.path.dirname(abs_out) or ".", exist_ok=True)
        _SESSIONS[session_id].save(abs_out)
        print(f"[DEBUG] Successfully saved to {abs_out}", file=sys.stderr)
        return {"ok": True, "output_path": abs_out}
    except Exception as e:
        print(f"[ERROR] Save failed: {e}", file=sys.stderr)
        return {"ok": False, "error": str(e)}


if __name__ == "__main__":
    # `transport="stdio"` is required because the agent uses stdio-based MCP clients.
    mcp.run(transport="stdio")
