"""
MCP Server — PPT writer (in-memory state + save to .pptx).

This server is started by `agent_ppt.py` using an MCP stdio transport, so it
must not rely on HTTP ports. Tools return JSON-serializable dicts so the
connected agent can safely parse responses.

**Tool index (for LLM / Claude system prompts):**

- ``create_pptx`` — start deck; returns ``session_id``.
- ``open_presentation`` — load existing ``.pptx`` from disk; append slides then ``save_presentation``.
- ``add_slide`` — title + bullets; returns ``slide_index``.
- ``add_text_box`` — free text at coordinates (inches).
- ``add_image`` — embed PNG/JPG from disk path or placeholder.
- ``add_smart_art`` — SmartArt-like row of labeled boxes (2–5 steps).
- ``apply_slide_accent`` — hex accent color on title/body.
- ``save_presentation`` — write safe ``.pptx`` to ``output_path``.
"""

import logging  # Quiet MCP request INFO lines when spawned as stdio subprocess.
import os  # Needed for creating output folders on save.
import uuid  # Needed to generate unique session ids per presentation.
import sys
from pathlib import Path

logging.getLogger("mcp").setLevel(logging.WARNING)
logging.getLogger("httpx").setLevel(logging.WARNING)
from typing import Dict, List  # Used to type the tool inputs/outputs.

from mcp.server.fastmcp import FastMCP  # FastMCP provides a minimal MCP server.
from pptx import Presentation  # python-pptx builds a real PowerPoint file.
from pptx.dml.color import RGBColor  # RGBColor is required to set theme accents.
from pptx.enum.shapes import MSO_SHAPE  # MSO_SHAPE is used to create rectangles.
from pptx.util import Inches, Pt  # Inches for layout; Pt for font sizes.
from pptx.enum.text import MSO_AUTO_SIZE


mcp = FastMCP("ppt-mcp-server")  # MCP server name (shows up in tooling).

# Keep presentation objects in memory so the agent can call:
# create_pptx -> add_slide (multiple times) -> save_presentation.
_SESSIONS: Dict[str, Presentation] = {}


def _parse_hex_color(accent_hex: str) -> RGBColor:
    """
    Convert a hex string like '#1F77B4' or '1F77B4' into an `RGBColor`.

    We keep this helper small and defensive because the system
    should not crash if a tool argument is malformed.
    """
    value = accent_hex.strip().lstrip("#")
    if len(value) != 6:
        # Fallback to a safe color if parsing fails.
        return RGBColor(31, 119, 180)

    r = int(value[0:2], 16)
    g = int(value[2:4], 16)
    b = int(value[4:6], 16)
    return RGBColor(r, g, b)


@mcp.tool()
def check_permissions(output_path: str) -> dict:
    """Test tool to verify write permissions on a path."""
    try:
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        with open(output_path, "w") as f:
            f.write("OK")
        return {"ok": True, "written_to": output_path}
    except Exception as e:
        return {"ok": False, "error": str(e)}


@mcp.tool()
def create_pptx(title: str = "Presentation") -> dict:
    """Create a new PowerPoint presentation with a professional title slide.

    I needed a way to start presentations programmatically, so this function
    sets up the basic structure with a nice dark theme and returns a session ID
    that we can use to add more slides later.

    Args:
        title: The main title for your presentation (shows up on first slide)

    Returns:
        Dictionary with success status and unique session ID for后续 operations
    """

    pres = Presentation()
    slide = pres.slides.add_slide(pres.slide_layouts[0])
    
    # 🎨 THEME: TITLE SLIDE (SLIDE 1)
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(15, 25, 45) # Deep Midnight Navy

    # Title Positioning & High-End Style
    title_shape = slide.shapes.title
    title_shape.text = title
    for tr in title_shape.text_frame.paragraphs[0].runs:
        tr.font.color.rgb = RGBColor(255, 223, 128)
        tr.font.size = Pt(44)
        tr.font.bold = True
    
    # Subtitle with Generated info
    subtitle = slide.placeholders[1]
    subtitle.text = "Generated by MDP Presentation Engine"
    sr = subtitle.text_frame.paragraphs[0].runs[0]
    sr.font.color.rgb = RGBColor(100, 150, 200) # Soft Sky Blue
    sr.font.size = Pt(18)

    session_id = str(uuid.uuid4())
    _SESSIONS[session_id] = pres
    return {"ok": True, "session_id": session_id}


@mcp.tool()
def open_presentation(file_path: str) -> dict:
    """Open an existing PowerPoint file so we can add more slides to it.

    Sometimes you want to edit an existing presentation instead of starting
    from scratch. This function loads the file and gives you a session ID
    to work with, just like create_pptx does.

    Args:
        file_path: Path to the .pptx file you want to edit

    Returns:
        Info about the loaded presentation or error if something went wrong
    """
    path = os.path.normpath(os.path.expanduser(file_path))
    path = os.path.abspath(path)
    if not os.path.isfile(path):
        return {"ok": False, "error": f"File not found: {path}"}
    try:
        pres = Presentation(path)
    except Exception as exc:
        return {"ok": False, "error": f"Could not open presentation: {exc}"}
    session_id = str(uuid.uuid4())
    _SESSIONS[session_id] = pres
    return {
        "ok": True,
        "session_id": session_id,
        "slides_total": len(pres.slides),
        "loaded_from": path,
    }


@mcp.tool()
def add_slide(session_id: str, slide_title: str, bullets: List[str]) -> dict:
    """Add a new slide with title and bullet points to your presentation.

    This is the workhorse function for building presentations. It creates
    a nicely formatted slide with your title and content, applying the same
    professional dark theme as the title slide.

    Args:
        session_id: The session ID from create_pptx or open_presentation
        slide_title: What you want the slide title to be
        bullets: List of bullet points (3-6 works best)

    Returns:
        Success status and the new slide's index
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}

    pres = _SESSIONS[session_id]
    slide = pres.slides.add_slide(pres.slide_layouts[1])
    slide_index = len(pres.slides) - 1
    
    # 🎨 THEME UPGRADE: PRO DARK SCIENTIFIC THEME (Stable API)
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(15, 25, 45) # Deep Midnight Navy

    # 🏷️ TITLE ALIGNMENT: Full-Width Lock
    slide.shapes.title.text = slide_title
    slide.shapes.title.left = Inches(0.5)
    slide.shapes.title.top = Inches(0.4)
    slide.shapes.title.width = int(pres.slide_width * 0.9)
    
    title_para = slide.shapes.title.text_frame.paragraphs[0]
    for tr in title_para.runs:
        tr.font.color.rgb = RGBColor(255, 223, 128)
        tr.font.bold = True
        tr.font.size = Pt(36)

    # 📝 MATTER ALIGNMENT: Below the Title
    body = slide.shapes.placeholders[1]
    body.left = Inches(0.5)
    body.top = Inches(1.8)
    body.width = int(pres.slide_width * 0.95)
    body.height = int(pres.slide_height * 0.6)
    
    tf = body.text_frame
    tf.word_wrap = True
    # TEXT_TO_FIT_SHAPE can shrink text to illegible in some viewers; NONE keeps readable size.
    tf.auto_size = MSO_AUTO_SIZE.NONE
    tf.clear()
    tf.margin_bottom = tf.margin_top = tf.margin_left = tf.margin_right = Inches(0.05)

    def _style_body_run(paragraph, size_pt: int = 18) -> None:
        """Assign RGB on runs — theme inheritance often yields black-on-navy (looks blank)."""
        for run in paragraph.runs:
            run.font.size = Pt(size_pt)
            run.font.color.rgb = RGBColor(220, 230, 240)

    use = [str(b).strip() for b in (bullets or []) if str(b).strip()][:5]
    if use:
        for i, bullet in enumerate(use):
            p = tf.add_paragraph() if i > 0 else tf.paragraphs[0]
            raw = str(bullet).strip()
            if raw.startswith("•"):
                raw = raw[1:].strip()
            if raw.startswith("\u2022"):
                raw = raw[1:].strip()
            if not raw:
                continue
            p.text = raw
            p.level = 0
            _style_body_run(p)
    if not tf.text.strip():
        tf.text = "Add research or model output: no bullet text was provided for this slide."
        _style_body_run(tf.paragraphs[0])

    # Sleek Designer Bottom Ribbon
    ribbon = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, pres.slide_height - Inches(0.1), pres.slide_width, Inches(0.1))
    ribbon.fill.solid()
    ribbon.fill.fore_color.rgb = RGBColor(0, 112, 192) # Vibrant Science Blue
    ribbon.line.fill.background()
    
    return {"ok": True, "slides_total": len(pres.slides), "slide_index": slide_index}


@mcp.tool()
def add_image(session_id: str, slide_index: int, image_path: str = "", caption: str = "") -> dict:
    """Add an image to the RIGHT half of a slide.

    **Required Tool Name:** add_image.

    **Parameters:**
        session_id: Session ID.
        slide_index: Slide to edit.
        image_path: Path to .jpg/.png.
        caption: Display text if missing.

    **Returns:** ``ok``, ``slide_index``.
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}
    pres = _SESSIONS[session_id]
    try:
        slide = pres.slides[slide_index]
    except Exception:
        return {"ok": False, "error": "Invalid slide_index"}

    # Position on the right 40% of the slide.
    left = int(pres.slide_width * 0.60)
    top = int(pres.slide_height * 0.25)
    width = int(pres.slide_width * 0.35)
    height = int(pres.slide_height * 0.60)

    if image_path and Path(image_path).is_file():
        try:
            slide.shapes.add_picture(image_path, left, top, width, height)
            return {"ok": True, "type": "file", "slide_index": slide_index}
        except Exception:
            pass
    
    # Placeholder
    shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, width, height)
    shape.fill.solid()
    shape.fill.fore_color.rgb = RGBColor(245, 245, 245)
    tf = shape.text_frame
    tf.clear()
    tf.text = caption or "Illustration Here"
    return {"ok": True, "type": "placeholder", "slide_index": slide_index}


@mcp.tool()
def apply_slide_accent(session_id: str, slide_index: int, accent_hex: str) -> dict:
    """Apply an **accent color** (hex) to title and body text on one slide.

    **Purpose:** Consistent visual theme across slides without manual formatting.

    **Parameters:**
        session_id: Active session.
        slide_index: Slide to style.
        accent_hex: Color like ``#1F77B4`` or ``1F77B4``; invalid values fall back to a default blue.

    **Returns:** ``ok``, ``slide_index``, ``accent_hex``.

    **Notes:** Best-effort; if a shape has no runs, styling may skip silently.
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}

    pres = _SESSIONS[session_id]
    try:
        slide = pres.slides[slide_index]
    except Exception:
        return {"ok": False, "error": "Invalid slide_index"}

    rgb = _parse_hex_color(accent_hex)

    # 1) Title accent
    try:
        title_shape = slide.shapes.title
        if title_shape is not None and getattr(title_shape, "text_frame", None) is not None:
            for paragraph in title_shape.text_frame.paragraphs:
                for run in paragraph.runs:
                    run.font.color.rgb = rgb
                    # Make title slightly larger for visual hierarchy.
                    run.font.size = Pt(30)
    except Exception:
        # Ignore styling errors; never fail the whole PPT generation.
        pass

    # 2) Bullets accent (placeholders are paragraph/runs-based)
    try:
        body_placeholder = slide.shapes.placeholders[1]
        tf = body_placeholder.text_frame
        for paragraph in tf.paragraphs:
            for run in paragraph.runs:
                run.font.color.rgb = rgb
    except Exception:
        pass

    return {"ok": True, "slide_index": slide_index, "accent_hex": accent_hex}


@mcp.tool()
def add_text_box(
    session_id: str,
    slide_index: int,
    text: str,
    left_inches: float = 0.5,
    top_inches: float = 5.0,
    width_inches: float = 8.5,
    height_inches: float = 1.2,
) -> dict:
    """Add a **free-floating text box** on a slide (caption, footer, callout).

    **Purpose:** Extra labels beyond the main title/bullet placeholder.

    **Parameters:**
        session_id: Active session.
        slide_index: Target slide index.
        text: Plain text (word-wrapped in the box).
        left_inches, top_inches, width_inches, height_inches: Position and size in inches.

    **Returns:** ``ok``, ``slide_index``, ``shape_index`` (last shape on slide).

    **Notes:** Coordinates are typical US Letter / 16:9 friendly defaults; adjust per theme.
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}
    pres = _SESSIONS[session_id]
    try:
        slide = pres.slides[slide_index]
    except Exception:
        return {"ok": False, "error": "Invalid slide_index"}

    box = slide.shapes.add_textbox(
        Inches(left_inches),
        Inches(top_inches),
        Inches(width_inches),
        Inches(height_inches),
    )
    tf = box.text_frame
    tf.clear()
    tf.text = text
    try:
        for p in tf.paragraphs:
            for r in p.runs:
                r.font.size = Pt(12)
    except Exception:
        pass
    return {"ok": True, "slide_index": slide_index, "shape_index": len(slide.shapes) - 1}


@mcp.tool()
def add_smart_art(session_id: str, slide_index: int, steps: List[str]) -> dict:
    """Draw a **simple process-style diagram** (SmartArt-like): boxes in a row with arrows.

    **Required Tool Name:** add_smart_art (per brief).

    **Parameters:**
        session_id: Active session.
        slide_index: Slide to draw on.
        steps: 2–5 short stage labels.

    **Returns:** ``ok``, ``slide_index``.
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}
    pres = _SESSIONS[session_id]
    try:
        slide = pres.slides[slide_index]
    except Exception:
        return {"ok": False, "error": "Invalid slide_index"}

    clean = [s.strip() for s in steps if s.strip()][:5]
    if len(clean) < 2:
        return {"ok": False, "error": "Provide at least 2 steps"}

    sw = pres.slide_width
    sh = pres.slide_height
    n = len(clean)
    margin = int(sw * 0.05)
    box_w = int((sw - 2 * margin) / n * 0.85)
    box_h = int(sh * 0.12)
    top = int(sh * 0.35)
    gap = int((sw - 2 * margin - n * box_w) / max(n - 1, 1))

    for i, label in enumerate(clean):
        left = margin + i * (box_w + gap)
        shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, left, top, box_w, box_h)
        shape.fill.solid()
        shape.fill.fore_color.rgb = RGBColor(240, 248, 255)
        shape.line.color.rgb = RGBColor(100, 149, 237)
        tf = shape.text_frame
        tf.clear()
        tf.text = label
        try:
            for p in tf.paragraphs:
                for r in p.runs:
                    r.font.size = Pt(11)
        except Exception:
            pass

    return {"ok": True, "slide_index": slide_index, "steps_drawn": n}


@mcp.tool()
def delete_slide(session_id: str, slide_index: int) -> dict:
    """Remove a slide from your presentation.

    Sometimes you make a mistake or want to reorganize. This function lets you
    remove any slide by its position number (starting from 0 for the first
    content slide after the title).

    Args:
        session_id: Your presentation session ID
        slide_index: Which slide to remove (0-based indexing)

    Returns:
        Success status and updated slide count
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}

    pres = _SESSIONS[session_id]
    try:
        # Validate slide index
        if slide_index < 0 or slide_index >= len(pres.slides):
            return {"ok": False, "error": f"Invalid slide_index: {slide_index}"}
        
        # Get the slide and its slide ID list entry
        slide = pres.slides[slide_index]
        sldId = pres.slides._sldIdLst[slide_index]
        
        # Remove the slide ID from the list
        pres.slides._sldIdLst.remove(sldId)
        
        return {"ok": True, "slides_total": len(pres.slides), "deleted_index": slide_index}
    except Exception as e:
        return {"ok": False, "error": f"Failed to delete slide: {str(e)}"}


@mcp.tool()
def get_slide_info(session_id: str, slide_index: int = -1) -> dict:
    """Check what slides you have in your presentation.

    This is useful for debugging or when you need to see what's already
    in your presentation before adding more slides. You can check all slides
    at once or just one specific slide.

    Args:
        session_id: Your presentation session ID
        slide_index: Which slide to check (-1 for all slides)

    Returns:
        List of slide information including titles and content status
    """
    if session_id not in _SESSIONS:
        return {"ok": False, "error": "Invalid session_id"}

    pres = _SESSIONS[session_id]
    slides_info = []

    try:
        if slide_index == -1:
            # Get all slides
            for i, slide in enumerate(pres.slides):
                slide_info = {
                    "index": i,
                    "title": "",
                    "has_content": False
                }
                
                # Try to get title
                if slide.shapes.title:
                    slide_info["title"] = slide.shapes.title.text or ""
                
                # Check if slide has content beyond title
                if len(slide.shapes) > 1:
                    slide_info["has_content"] = True
                
                slides_info.append(slide_info)
        else:
            # Get specific slide
            if slide_index < 0 or slide_index >= len(pres.slides):
                return {"ok": False, "error": f"Invalid slide_index: {slide_index}"}
            
            slide = pres.slides[slide_index]
            slide_info = {
                "index": slide_index,
                "title": slide.shapes.title.text if slide.shapes.title else "",
                "shapes_count": len(slide.shapes),
                "has_content": len(slide.shapes) > 1
            }
            slides_info.append(slide_info)

        return {"ok": True, "slides_info": slides_info, "total_slides": len(pres.slides)}
    except Exception as e:
        return {"ok": False, "error": f"Failed to get slide info: {str(e)}"}


@mcp.tool()
def save_presentation(session_id: str, output_path: str) -> dict:
    """Save your presentation as a PowerPoint file.

    This is the final step - once you're happy with your presentation,
    call this function to save it as a .pptx file that you can open
    in PowerPoint or share with others.

    Args:
        session_id: Your presentation session ID
        output_path: Where you want to save the file (.pptx extension)

    Returns:
        Success status and the full path where the file was saved
    """
    # Debug print to server stderr (seen by agent)
    print(f"[DEBUG] Saving session {session_id} to {output_path}", file=sys.stderr)
    
    if session_id not in _SESSIONS:
        print(f"[ERROR] Session {session_id} not found in _SESSIONS: {list(_SESSIONS.keys())}", file=sys.stderr)
        return {"ok": False, "error": f"Invalid session_id: {session_id}"}

    try:
        # Create output folder if it doesn't exist.
        abs_out = os.path.abspath(output_path)
        os.makedirs(os.path.dirname(abs_out) or ".", exist_ok=True)
        _SESSIONS[session_id].save(abs_out)
        print(f"[DEBUG] Successfully saved to {abs_out}", file=sys.stderr)
        return {"ok": True, "output_path": abs_out}
    except Exception as e:
        print(f"[ERROR] Save failed: {e}", file=sys.stderr)
        return {"ok": False, "error": str(e)}


if __name__ == "__main__":
    # `transport="stdio"` is required because the agent uses stdio-based MCP clients.
    mcp.run(transport="stdio")
